In [1]:
import numpy as np
import pandas as pd

In [8]:
# build a dataframe
dict_df = {'0 column': ['age' , 'articles' , 'experiments' , 'ability for study'],
            'age' : [1 , 0.2 , 0.33 , 0.14],
            'articles' : [5 , 1 , 1 , 0.33],
            'experiments' : [3 , 1 , 1 , 0.33],
            'ability for study' : [7 , 3 , 3 , 1]}
df_com_criteria = pd.DataFrame(dict_df)
df = df_com_criteria.set_index('0 column')
df

age  articles  experiments  ability for study
0 column                                                         
age                1.00      5.00         3.00                  7
articles           0.20      1.00         1.00                  3
experiments        0.33      1.00         1.00                  3
ability for study  0.14      0.33         0.33                  1

In [11]:
matrix = np.array(df)
matrix

array([[1.  , 5.  , 3.  , 7.  ],
       [0.2 , 1.  , 1.  , 3.  ],
       [0.33, 1.  , 1.  , 3.  ],
       [0.14, 0.33, 0.33, 1.  ]])

In [54]:
# calculate the weight of matrix
def weight(input_matrix):
    d = input_matrix / np.sum(input_matrix , axis=0)
    a = np.sum(d , axis=1) / input_matrix.shape[0]
    return a
weight(matrix)

array([0.5859456 , 0.16452228, 0.18398335, 0.06554877])

In [77]:
# now, build matrices for every indicators
dict_age = {'professors' : ['A' , 'B' , 'C'],
            'A': [1 , 0.33 , 0.5],
            'B': [3 , 1 , 1],
            'C': [2 , 1 , 1]}
df_alt_age = pd.DataFrame(dict_age).set_index('professors')
matrix_age = np.array(df_alt_age)
weight_age = weight(matrix_age)
dict_articles = {'professors' : ['A' , 'B' , 'C'],
            'A': [1 , 0.2 , 0.11],
            'B': [5 , 1 , 0.33],
            'C': [9 , 3 , 1]}
df_alt_articles = pd.DataFrame(dict_articles).set_index('professors')
matrix_articles = np.array(df_alt_articles)
weight_articles = weight(matrix_articles)
dict_experiments = {'professors' : ['A' , 'B' , 'C'],
            'A': [1 , 0.143 , 0.143],
            'B': [7 , 1 , 0.5],
            'C': [7 , 2 , 1]}
df_alt_experiments = pd.DataFrame(dict_experiments).set_index('professors')
matrix_experiments = np.array(df_alt_experiments)
weight_experiments = weight(matrix_experiments)
dict_study = {'professors' : ['A' , 'B' , 'C'],
            'A': [1 , 3 , 0.25],
            'B': [0.33 , 1 , 0.17],
            'C': [4 , 6 , 1]}
df_alt_study = pd.DataFrame(dict_study).set_index('professors')
matrix_study = np.array(df_alt_study)
weight_study = weight(matrix_study)

In [91]:
# multiply weight of indicarors to weight of main matrix
matrix_criteria = np.array([weight_age , weight_articles , weight_experiments , weight_study]).T
np.dot(matrix_criteria , weight(matrix))

array([0.6037411 , 0.22101211, 0.17524679])

professor A is choosen